# Generated by Django 5.0.7 on 2024-07-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(choices=[('durban', 'durban')], default='durban', max_length=50)),
                ('roll_type', models.CharField(choices=[('full_title', 'full_title'), ('sectional_title', 'sectional_title')], max_length=50)),
                ('rate_number', models.CharField(max_length=200)),
                ('legal_description', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('first_owner', models.CharField(max_length=200)),
                ('use_code', models.CharField(max_length=200)),
                ('rating_category', models.CharField(max_length=200)),
                ('market_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('registered_extent', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
