# Generated by Django 5.0.7 on 2024-07-27 17:38

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuation',
            name='city',
            field=models.CharField(choices=[('durban', 'durban')], db_default='durban', default='durban', max_length=50),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
