# Generated by Django 5.0.7 on 2024-07-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0002_alter_valuation_city_alter_valuation_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuation',
            name='market_value',
            field=models.DecimalField(decimal_places=3, max_digits=40),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='registered_extent',
            field=models.DecimalField(decimal_places=3, max_digits=40),
        ),
    ]
